name: CI

on:
  push:
    branches:
      - main  # Du kannst hier den Namen deiner Hauptbranch anpassen

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 17

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew  # Stelle sicher, dass das Gradlew-Skript ausführbar ist

      - name: Clean Build and Run Tests
        run: |
          ./gradlew clean test --info --stacktrace
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.9-9/x64




